function MASK = SegmentXeLung(V,MASK)
%Image Processing Function
%
% V      - RGB or grayscale volume V that corresponds to the image data of 
%          the volume during automation.
% MASK   - A logical array where the first three dimensions match the first 
%          three dimensions of input volume V. If the user has already 
%          created a labeled region, MASK may have voxels labeled as true 
%          when passed to this function.
%

%--------------------------------------------------------------------------
% Auto-generated by the Volume Segmenter App. 
%
% When used by the App, this function will be called once to process the
% volume as specified by the user.
%
%--------------------------------------------------------------------------


% Replace the sample below with your code----------------------------------

% if ~any(MASK(:))
    % No initial mask, generate one
    nzcof = 1; 
    SE = 1;
    Image = V(:,:,:,1);
    Image = Image./max(Image(:));
    [counts,~] = imhist(Image,16);
    T = otsuthresh(counts);
    mask = imbinarize(Image,T.*nzcof);

    %errosion/dilation
    [x2,y2]=meshgrid(-SE:SE,-SE:SE); 
    nhood2=x2.^2+y2.^2<=SE^2;
    se1=strel('arbitrary',nhood2);
    mask_erode=imerode(mask,se1);
    
% end

MASK = imdilate(mask_erode,se1); % apply mask    

%--------------------------------------------------------------------------
