
function R_So_Model_Animal_1D=LM_Model_R_So_Animal_1D(ky,num_bavlue)
    formatSpec_y = '    for (i in 1:%d){';
    formatSpec_b = '        for (l in 1:%d){';
    formatSpec_b2 = '            MSR[i] <- sum(residual.sq[i,])/%d';

    str_y = sprintf(formatSpec_y,ky);
    str_b = sprintf(formatSpec_b,num_bavlue);
    str_b2 = sprintf(formatSpec_b2,num_bavlue);
    
    R_So_Model_Animal_1D = fopen('R_So_Model_Animal_1D.txt','wt');
    fprintf(R_So_Model_Animal_1D, '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', 'model <- function()'...
                             ,'{'...
                             ,    str_y...
                             ,'        D_LO[i]<- Do*exp(-2.89*pow((1-((R[i]-h[i])/R[i])),1.78))'...
                             ,'        Beta_L[i]<- 35.6*pow((R[i]/L1),1.5)*exp(-4/sqrt( (1-((R[i]-h[i])/R[i]))))'...
                             ,'        A[i]<- 1.3+0.25*exp(14*pow(R[i]/L2,2))'...
                             ,'        u[i]<- exp(-A[i]*pow((1-((R[i]-h[i])/R[i])),2))*(exp(-5*pow((1-((R[i]-h[i])/R[i])),2))+5*pow((1-((R[i]-h[i])/R[i])),2)-1)'...
                             ,'        D_TO[i]<- Do*exp(-0.73*pow((L2/R[i]),1.4))*(1+u[i])'...
                             ,'        Beta_T[i] <- 0.06'...
                             ,      str_b...
                             ,'            DL[i,l]<- D_LO[i]*(1-(Beta_L[i]*b[l]*D_LO[i]))'...
                             ,'            DT[i,l]<- D_TO[i]*(1+(Beta_T[i]*b[l]*D_TO[i]))'...
                             ,'            Dan[i,l]<- abs(DL[i,l]-DT[i,l])'...
                             ,'            x[i,l] <- sqrt(b[l]*Dan[i,l])'...
                             ,'            phi.deno[i,l] <-  1+a1*x[i,l]+a2*pow(x[i,l], 2)+a3*pow(x[i,l], 3)+a4*pow(x[i,l], 4)'...
                             ,'            phi.approx[i,l] <- 1-pow(phi.deno[i,l], -4)'...
                             ,'            lambda[i, l] <- ( pow(So[i],2)*exp(-2*b[l]*DT[i,l])*(3.14/(4*b[l]*Dan[i,l]))*pow(phi.approx[i,l],2) )/(2*pow(sigma[l],2))'...                              
                             ,'            p[i, l] ~ dpois(lambda[i, l])'...
                             ,'            kk[i, l] <- 2 * p[i, l] + 2'...
                             ,'            M[i, l] ~ dchisqr(kk[i, l])'...
                             ,'            residual[i, l] <- M[i, l] - kk[i, l]'...                             
                             ,'            residual.sq[i, l] <- pow((M[i, l]- kk[i, l]), 2)'...
                             ,'            }'...
                             ,'            So[i] ~ dunif(0.0001, 200)'...
                             ,'            h[i] ~ dunif(10.0E-4 , 80.0E-4)'...
                             ,'            R[i] ~ dunif(50.0E-4 , 145.0E-4)'...
                             ,str_b2...
                             ,'    }'...
                             ,'}');
    fclose(R_So_Model_Animal_1D);
end
