
function D_Model_Animal_1D=LM_Model_D_Animal_1D(ky,num_bavlue)
%   Inputs:
%      
%   Outputs:
%                   
%   Package: https://github.com/aboodbdaiwi/HP129Xe_Analysis_App
%
%   Author: Abdullah S. Bdaiwi
%   Work email: abdullah.bdaiwi@cchmc.org
%   Personal email: abdaiwi89@gmail.com
%   Website: https://www.cincinnatichildrens.org/research/divisions/c/cpir
%
%   Please add updates at the end. Ex: 3/10/24 - ASB: update .... 
    
    formatSpec_y = '    for (i in 1:%d)';
    formatSpec_b = '        for (l in 1:%d)';
    formatSpec_b2 = '            #MSR[i] <- sum(residual.sq[i,])/%d';
    
    str_y = sprintf(formatSpec_y,ky);
    str_b = sprintf(formatSpec_b,num_bavlue);
    str_b2 = sprintf(formatSpec_b2,num_bavlue);
    
    D_Model_Animal_1D = fopen('LM_Model_D_Animal_1D.txt','wt');
    fprintf(D_Model_Animal_1D, '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', 'model <- function()'...
                             ,'{'...
                             ,    str_y...
                             ,'    {'...
                             ,      str_b...
                             ,'            {'...
                             ,'            x[i,l] <- sqrt(b[l]*Dan[i])'...
                             ,'            phi.deno[i,l] <- 1+a1*x[i,l]+a2*pow(x[i,l], 2)+a3*pow(x[i,l], 3)+a4*pow(x[i,l], 4)'...
                             ,'            phi.approx[i,l] <- 1-pow(phi.deno[i,l], -4)'...
                             ,'            lambda[i, l] <- ( pow(So[i],2)*exp(-2*b[l]*DT[i])*(3.14/(4*b[l]*Dan[i]))*pow(phi.approx[i,l],2) )/(2*pow(sigma[l],2))'...                              
                             ,'            p[i, l] ~ dpois(lambda[i, l])'...
                             ,'            kk[i, l] <- 2 * p[i, l] + 2'...
                             ,'            M[i, l] ~ dchisqr(kk[i, l])'...
                             ,'            #residual[i, l] <- M[i, l] - kk[i, l]'...
                             ,'            #residual.sq[i, l] <- pow(residual[i, l], 2)'...                             
                             ,'            }'...
                             ,'            So[i] ~ dunif(0.0001, 200)'...
                             ,'            DT[i] ~ dunif(0.001, 0.06)'...
                             ,'            Dan[i] ~ dunif(0.001, 0.06)'...
                             ,str_b2...                                                          
                             ,'    }'...
                             ,'}');
    fclose(D_Model_Animal_1D);
end
