
function R_So_Model_Animal_1D=LM_Model_R_So_Human_1D_h(ky,num_bavlue)
%   Inputs:
%      
%   Outputs:
%                   
%   Package: https://github.com/aboodbdaiwi/HP129Xe_Analysis_App
%
%   Author: Abdullah S. Bdaiwi
%   Work email: abdullah.bdaiwi@cchmc.org
%   Personal email: abdaiwi89@gmail.com
%   Website: https://www.cincinnatichildrens.org/research/divisions/c/cpir
%
%   Please add updates at the end. Ex: 3/10/24 - ASB: update .... 
    
    formatSpec_y = '    for (i in 1:%d){';
    formatSpec_b = '        for (l in 1:%d){';
    formatSpec_b2 = '            MSR[i] <- sum(residual.sq[i,])/%d';
    
    str_y = sprintf(formatSpec_y,ky);
    str_b = sprintf(formatSpec_b,num_bavlue);
    str_b2 = sprintf(formatSpec_b2,num_bavlue);
    
    R_So_Model_Animal_1D = fopen('LM_Model_R_So_Human_1D_h.txt','wt');
    fprintf(R_So_Model_Animal_1D, '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', 'model <- function()'...
                             ,'{'...
                             ,    str_y...
                             ,'        D_LO[i]<- Do*exp(-2.81*pow((1-((R[i]-h[i])/R[i])),1.76))'...
                             ,'        Beta_L[i]<- 21.2*pow((R[i]/L1),1.5)*exp(-3.65*pow( (1-((R[i]-h[i])/R[i])),-0.5))'...
                             ,'        c1[i]<- 1.13*(R[i]/L2)-1.40 *pow((R[i]/L2),2)'...
                             ,'        c2[i]<- 3.55-11.27*(R[i]/L2)+7.44 *pow((R[i]/L2),2)'...
                             ,'        u[i]<- c1[i]*(1-((R[i]-h[i])/R[i]))+c2[i]*pow((1-((R[i]-h[i])/R[i])),2)'...
                             ,'        D_TO[i]<- Do*exp(-0.74*pow((L2/R[i]),1.47))*(1+u[i])'...
                             ,'        cc0[i]<- 1.89-5.82*(R[i]/L2)+3.60 *pow((R[i]/L2),2)'...
                             ,'        cc1[i]<- -4.21+14.1*(R[i]/L2)-9.52 *pow((R[i]/L2),2)'...
                             ,'        cc2[i]<- 2.14-7.35*(R[i]/L2)+5.03 *pow((R[i]/L2),2)'...
                             ,'        Beta_T[i]<- cc0[i]+cc1[i]*((R[i]-h[i])/R[i])+cc2[i]*pow(((R[i]-h[i])/R[i]),2)'...
                             ,      str_b...
                             ,'            DL[i,l]<- D_LO[i]*(1-(Beta_L[i]*b[l]*D_LO[i]))'...
                             ,'            DT[i,l]<- D_TO[i]*(1+(Beta_T[i]*b[l]*D_TO[i]))'...
                             ,'            Dan[i,l]<- abs(DL[i,l]-DT[i,l])'...
                             ,'            x[i,l] <- sqrt(b[l]*Dan[i,l])'...
                             ,'            phi.deno[i,l] <-  1+a1*x[i,l]+a2*pow(x[i,l], 2)+a3*pow(x[i,l], 3)+a4*pow(x[i,l], 4)'...
                             ,'            phi.approx[i,l] <- 1-pow(phi.deno[i,l], -4)'...
                             ,'            lambda[i, l] <- ( pow(So[i],2)*exp(-2*b[l]*DT[i,l])*(3.14/(4*b[l]*Dan[i,l]))*pow(phi.approx[i,l],2) )/(2*pow(sigma[l],2))'...                              
                             ,'            p[i, l] ~ dpois(lambda[i, l])'...
                             ,'            kk[i, l] <- 2 * p[i, l] + 2'...
                             ,'            M[i, l] ~ dchisqr(kk[i, l])'...
                             ,'            residual[i, l] <- M[i, l] - kk[i, l]'...
                             ,'            residual.sq[i, l] <- pow(residual[i, l], 2)'...
                             ,'            }'...
                             ,'            So[i] ~ dunif(0.0001, 200)'...
                             ,'            h[i] ~ dunif(50.0E-4 , 200.0E-4)'...
                             ,'            R[i] ~ dunif(230.0E-4 , 400.0E-4)'...
                             ,str_b2...                             
                             ,'    }'...
                             ,'}');
    fclose(R_So_Model_Animal_1D);
end
