
function CCHMC_Db_GX_Pipeline_NoData(MainInput)

analysisSubfolder = fullfile(MainInput.analysisfolder, 'GasExchange_Analysis');
if ~exist(analysisSubfolder, 'dir')
    mkdir(analysisSubfolder);
end
   scan_num = 1;
   AnalysisCode_path = 'https://github.com/aboodbdaiwi/XIPline';
   AnalysisDate = str2double(datestr(datetime('today'), 'yyyymmdd'));
    % JSON file
    clc;
    headers = {'SUBJECT_ID','Age','Sex','Disease','ScanDate','ScanTime','scan_num','CalibrationDataPath','DissolvedDataPath','AnatomicalDataPath','gx_analysis_folder','Note','ImageQuality','Scanner', ...
               'ScannerSoftware','SequenceType','ReconType','ScanVersion','AnalysisCode_path','AnalysisDate','AnalysisVersion','AnalysisCode_hash',...
               'Denoise','N4Bias','AnalysisMethod','AgeCorrection','Spectral_SNR','k0_fit','TE90','Actual_TE90','Flip_Angle_Factor', ...
               'Package_Version','Process_Date','Healthy_Cohort', ...
               'Gas_Frequency','Barrier_Frequency','RBC_Frequency', ...
               'Gas_T2star','Barrier_T2star','Barrier_LtoG_ratio','RBC_T2star', ...
               'Gas_Phase','Barrier_Phase','RBC_Phase', ...
               'Dixon_Phase_Separation','RBC_Barrier_Ratio','Gas_Contamination','Dixon_Phase_Shift', ...
               'Ventilation_SNR','Gas_SNR','Dissolved_SNR','CorrDissolved_SNR','Barrier_SNR','RBC_SNR', ...
               'Ventilation_Mean','Ventilation_Median','Ventilation_Std_Dev', ...
               'Dissolved_Mean','Dissolved_Median','Dissolved_Std_Dev', ...
               'Barrier_Uptake_Mean','Barrier_Uptake_Median','Barrier_Uptake_Std_Dev', ...
               'RBC_Transfer_Mean','RBC_Transfer_Median','RBC_Transfer_Std_Dev', ...
               'RBC2Barrier_Mean','RBCBarrier_Median','RBC2Barrier_Std_Dev', ...
               'RBC_Osc_K0','RBC_Osc_Mean','RBC_Osc_Std_Dev', ...
               'Ventilation_Bin1_Percent','Ventilation_Bin2_Percent','Ventilation_Bin3_Percent','Ventilation_Bin4_Percent','Ventilation_Bin5_Percent','Ventilation_Bin6_Percent', ...
               'Dissolved_Bin1_Percent','Dissolved_Bin2_Percent','Dissolved_Bin3_Percent','Dissolved_Bin4_Percent','Dissolved_Bin5_Percent','Dissolved_Bin6_Percent', ...
               'Barrier_Uptake_Bin1_Percent','Barrier_Uptake_Bin2_Percent','Barrier_Uptake_Bin3_Percent','Barrier_Uptake_Bin4_Percent','Barrier_Uptake_Bin5_Percent','Barrier_Uptake_Bin6_Percent','Barrier_Uptake_Bin7_Percent','Barrier_Uptake_Bin8_Percent', ...
               'RBC_Transfer_Bin1_Percent','RBC_Transfer_Bin2_Percent','RBC_Transfer_Bin3_Percent','RBC_Transfer_Bin4_Percent','RBC_Transfer_Bin5_Percent','RBC_Transfer_Bin6_Percent', ...
               'RBC2Barrier_Bin1_Percent','RBC2Barrier_Bin2_Percent','RBC2Barrier_Bin3_Percent','RBC2Barrier_Bin4_Percent','RBC2Barrier_Bin5_Percent','RBC2Barrier_Bin6_Percent', ...
               'RBC_Osc_Bin1_Percent','RBC_Osc_Bin2_Percent','RBC_Osc_Bin3_Percent','RBC_Osc_Bin4_Percent','RBC_Osc_Bin5_Percent','RBC_Osc_Bin6_Percent','RBC_Osc_Bin7_Percent','RBC_Osc_Bin8_Percent',...
               'woods_analysis_folder'};
    
    % --- Collect values in same order ---
    NewData = {MainInput.SubjectID, MainInput.Age,MainInput.Sex, MainInput.Disease,string(MainInput.ScanDate),'',scan_num,'','', '',MainInput.gx_analysis_folder,MainInput.Note,'1-Failed', MainInput.Scanner, ...
               MainInput.ScannerSoftware,MainInput.SequenceType,'','',AnalysisCode_path,string(AnalysisDate),MainInput.analysisversion,'',...
               MainInput.denoiseXe,MainInput.N4Bias,MainInput.AnalysisMethod,MainInput.AgeCor,'','', '', '', '', ...
               '', '', '', ...
               '', '', '', ...
               '', '', '', '', ...
               '', '', '',...%Spectro Fitting Results - Phase
               '', '', ...
               '', '', ...
               '', '', '', '', '', '', ...
               '', '', '', ...
               '', '', '', ...
               '', '', '', ...
               '', '', '', ...
               '', '', '', ...
               '', '', '', ...
               '', '', '', '', '', '', ...
               '', '', '', '', '', '', ...
               '', '', '', '', '', '', '', '', ...
               '', '', '', '', '', '', ...
               '', '', '', '', '', '', ...
               '', '', '', '', '', '', '', '', '' };

    % --- Convert into struct ---
    Outputs = cell2struct(NewData, headers, 2);
    OutputJSONFile = fullfile(MainInput.analysisfolder, ['GxAnalysis_','ser-',MainInput.timeStr,'.json']);
    Global.exportStructToJSON(Outputs, OutputJSONFile);

    clearvars

end

