function T = coerceExcelTypes(T)
    import VentilationFunctions.*
    vars = T.Properties.VariableNames;   % cell array of char

    targetStringVars = { ...
        'SubjectID',...
        'SubjectID_PO',...
        'Session', ...
        'Recon',...
        'Polarizer',...
        'Notes',...
        'ImageQuality',...
        'PROT_FILEPATH',...
        'Vent_path',...
        'SliceOrientation',...
        'InternalProcessingNotes',...
        'OtherInternalProcessingNotes',...
        'TRAVERSAL_GEO',...
        'Comments'...
        };

    tf = ismember(vars, targetStringVars);
    stringVars = vars(tf);

    for i = 1:numel(stringVars)
        vn = stringVars{i};
        T.(vn) = string(T.(vn));
        T.(vn) = strtrim(T.(vn));
        T.(vn) = cellstr(T.(vn));
    end

    targetNumericVars = { ...
        'XeSeriesNumber',...
        'ProtonSeriesNumber',...
        'FrequencyOffsetHz',...
        'Subject',...
        'RunMode',...
        'PIXEL_SPACING_X',...
        'PIXEL_SPACING_Y',...
        'SLICE_THICKNESS',...
        'AGE'...
        };

    tf = ismember(vars, targetNumericVars);
    numericVars = vars(tf);

    for i = 1:numel(numericVars)
        vn = numericVars{i};
        T.(vn) = coerceToDouble(T.(vn));
        T.(vn) = num2cell(T.(vn));
    end

    if ismember('Selected', vars)
        T.Selected = coerceToLogical(T.Selected);
    end

    if ismember('ScanDate', vars)
        T.ScanDate = normalizeScanDate(T.ScanDate);
    end
end